/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.main;

import com.fpt.DAO.AccountDao;
import com.fpt.DAO.UserDAO;
import com.fpt.Validate.Validate;
import com.fpt.entity.Account;
import com.fpt.entity.User;
import com.fpt.utils.Auth;
import com.fpt.utils.MsgBox;
import com.fpt.utils.XImage;
import com.raven.dialog.Message;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author ducit
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    String username;
    public Login() {
        initComponents();
        lbAlertPassword.setText("");
        lbAlertUsername.setText("");
        txtUser.grabFocus();
    }

    AccountDao dao = new AccountDao();

    public void backLogin() {
        txtUser.grabFocus();
    }

    public void clickLogin() {
        txtUser.setBackground(Color.white);
        txtPassWord.setBackground(Color.white);
        if (Validate.checkEmptyLogin(txtUser, "Không được để trống Username!") == false && Validate.checkEmptyLogin( txtPassWord, "Không được để trống password!") == false) {
            return;
        } else if (Validate.checkEmptyLogin(txtPassWord, "Không được để trống password!") == false) {
            return;
        } else {
            login();
        }
    }
    
    public boolean checkUsername(){
        if(txtUser.getText().isEmpty()){
            return false;
        }
        return true;
    }

    public boolean login() {
        String userName = txtUser.getText();
        String passWord = new String(txtPassWord.getPassword());
        UserDAO uDao = new UserDAO();

        try {
            Account account = dao.selectById(userName);
            if(Validate.checkEmptyLogin(txtUser, "Không được để trống Username!") == false){
                return false;
            }else if (account == null && userName.isEmpty() == false ) {    //nếu user sai
                lbAlertUsername.setText("Sai tên đăng nhập!");
                return false;
            } else {
                String passwordSystem = account.getPassWord();
                if (passWord.equals(passwordSystem)) {
                    MsgBox.alert(this, "Đăng nhập thành công!");
                    User user = uDao.selectById(account.getIdUser());
                    Auth.user = user;
                    new Main().setVisible(true);
                    this.setVisible(false);
                    return true;
                } else {
                    lbAlertPassword.setText("Sai mật khẩu!");
                    return false;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
        return true;

    }
    public void addEventRegister(ActionListener event) {
        btnForgot.addActionListener(event);
    }

    public void addEventLogin(ActionListener event) {
        btnLogin.addActionListener(event);
    }
    
    public String getUserName(){
        username = txtUser.getText();
        return username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new com.raven.suportSwing.TextField();
        btnLogin = new com.raven.suportSwing.MyButton();
        txtPassWord = new com.raven.suportSwing.PasswordField();
        btnForgot = new com.raven.suportSwing.MyButton();
        lbAlertUsername = new javax.swing.JLabel();
        lbAlertPassword = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserName1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtUser.setFont(new java.awt.Font("Saira ExtraCondensed Medium", 0, 20)); // NOI18N
        txtUser.setLabelText("\n");
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnLogin.setText("Đăng nhập");
        btnLogin.setBorderColor(new java.awt.Color(51, 153, 255));
        btnLogin.setColorClick(new java.awt.Color(255, 102, 204));
        btnLogin.setColorOver(new java.awt.Color(51, 153, 255));
        btnLogin.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 0, 20)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtPassWord.setFont(new java.awt.Font("Saira ExtraCondensed Medium", 0, 20)); // NOI18N
        txtPassWord.setLabelText("");
        txtPassWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassWordFocusGained(evt);
            }
        });
        txtPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassWordActionPerformed(evt);
            }
        });

        btnForgot.setBorderColor(new java.awt.Color(51, 153, 255));
        btnForgot.setColorClick(new java.awt.Color(255, 102, 204));
        btnForgot.setColorOver(new java.awt.Color(51, 153, 255));
        btnForgot.setContentAreaFilled(true);
        btnForgot.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 0, 20)); // NOI18N
        btnForgot.setLabel("Quên mật khẩu");
        btnForgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForgotActionPerformed(evt);
            }
        });

        lbAlertUsername.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 2, 14)); // NOI18N
        lbAlertUsername.setForeground(new java.awt.Color(255, 51, 0));
        lbAlertUsername.setText("jLabel1");

        lbAlertPassword.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 2, 14)); // NOI18N
        lbAlertPassword.setForeground(new java.awt.Color(255, 51, 0));
        lbAlertPassword.setText("jLabel1");

        lblUserName.setFont(new java.awt.Font("Saira ExtraCondensed ExtraBold", 0, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(25, 116, 211));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setText("User Name");

        lblUserName1.setFont(new java.awt.Font("Saira ExtraCondensed ExtraBold", 0, 18)); // NOI18N
        lblUserName1.setForeground(new java.awt.Color(25, 116, 211));
        lblUserName1.setText("PassWord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnForgot, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAlertPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassWord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbAlertUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlertUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbAlertPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        clickLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        lbAlertUsername.setText("");
    }//GEN-LAST:event_txtUserFocusGained

    private void txtPassWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassWordFocusGained
        lbAlertPassword.setText("");
    }//GEN-LAST:event_txtPassWordFocusGained

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassWordActionPerformed

    private void btnForgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForgotActionPerformed
        // TODO add your handling code here:
        username = txtUser.getText();
    }//GEN-LAST:event_btnForgotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.suportSwing.MyButton btnForgot;
    private com.raven.suportSwing.MyButton btnLogin;
    private javax.swing.JLabel lbAlertPassword;
    private javax.swing.JLabel lbAlertUsername;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private com.raven.suportSwing.PasswordField txtPassWord;
    private com.raven.suportSwing.TextField txtUser;
    // End of variables declaration//GEN-END:variables

}
