/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.main;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.time.Clock;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Admins
 */
public class VerifyEmail extends javax.swing.JPanel {

    /**
     * Creates new form VerifyEmail
     */
    int randomCode;
    String username;
    
    public VerifyEmail() {
        initComponents();
    }
    
    public boolean verifyEmail(){
        if (Integer.valueOf(txtVerify.getText()) == randomCode){
            return true;
        }
        lblVerify.setText("Mã xác nhận không đúng!!");
        return false;
    }
    
    public void addEventChangePass(ActionListener event) {
        btnVerify.addActionListener(event);
    }
    
    public void setVerifyCode(int randomCode){
        this.randomCode = randomCode;
    }
    
    public void setUsername(String username){
        this.username = username;
    }
    
    public String getUsername(){
        return username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVerify = new com.raven.suportSwing.TextField();
        btnVerify = new com.raven.suportSwing.MyButton();
        lblUserName = new javax.swing.JLabel();
        lblVerify = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(499, 385));

        txtVerify.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 0, 18)); // NOI18N
        txtVerify.setLabelText("Nhập mã xác minh");
        txtVerify.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVerifyFocusGained(evt);
            }
        });

        btnVerify.setText("Xác minh");
        btnVerify.setBorderColor(new java.awt.Color(61, 97, 133));
        btnVerify.setColorClick(new java.awt.Color(189, 231, 255));
        btnVerify.setColorOver(new java.awt.Color(61, 97, 133));
        btnVerify.setFont(new java.awt.Font("Saira ExtraCondensed SemiBold", 0, 20)); // NOI18N
        btnVerify.setMaximumSize(new java.awt.Dimension(95, 39));
        btnVerify.setMinimumSize(new java.awt.Dimension(95, 39));
        btnVerify.setPreferredSize(new java.awt.Dimension(95, 39));
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Saira ExtraCondensed ExtraBold", 0, 20)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(25, 116, 211));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setText("Mã xác minh đã được gửi tới email của bạn!");

        lblVerify.setFont(new java.awt.Font("Saira ExtraCondensed Medium", 2, 18)); // NOI18N
        lblVerify.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblUserName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(txtVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVerifyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVerifyFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVerifyFocusGained

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
       
    }//GEN-LAST:event_btnVerifyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.suportSwing.MyButton btnVerify;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblVerify;
    private com.raven.suportSwing.TextField txtVerify;
    // End of variables declaration//GEN-END:variables
}
